In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/causes-of-death-our-world-in-data/20222703 Causes Of Death Clean Output V2.0.csv
/kaggle/input/causes-of-death-our-world-in-data/20220327 annual-number-of-deaths-by-cause.csv

Mapping Based on overall # of death over times 
Regional (Country) mapping with filtered columns

In [2]:
#import dataset
causeOfDeath = pd.read_csv("/kaggle/input/causes-of-death-our-world-in-data/20222703 Causes Of Death Clean Output V2.0.csv")
annualDeathCases = pd.read_csv("/kaggle/input/causes-of-death-our-world-in-data/20220327 annual-number-of-deaths-by-cause.csv")

In [3]:
#eda first set
causeOfDeath.head()

,Causes name,Causes Full Description,Death Numbers,Entity,Code,Year
0,Meningitis,Deaths - Meningitis - Sex: Both - Age: All Age...,2933.0,Afghanistan,AFG,2007
1,Neoplasms,Deaths - Neoplasms - Sex: Both - Age: All Ages...,15925.0,Afghanistan,AFG,2007
2,"Fire, heat, and hot substances","Deaths - Fire, heat, and hot substances - Sex:...",481.0,Afghanistan,AFG,2007
3,Malaria,Deaths - Malaria - Sex: Both - Age: All Ages (...,393.0,Afghanistan,AFG,2007
4,Drowning,Deaths - Drowning - Sex: Both - Age: All Ages ...,2127.0,Afghanistan,AFG,2007

In [4]:
#shape value
print(causeOfDeath.shape)

(201762, 6)

In [5]:
#get col datatype and nulls
print(causeOfDeath.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201762 entries, 0 to 201761
Data columns (total 6 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Causes name              201762 non-null  object
 1   Causes Full Description  201762 non-null  object
 2   Death Numbers            190575 non-null  float64
 3   Entity                   201762 non-null  object
 4   Code                     200277 non-null  object
 5   Year                     201762 non-null  int64
dtypes: float64(1), int64(1), object(4)
memory usage: 9.2+ MB
None

In [6]:
# use to see all unique values
for col in causeOfDeath:
  print(causeOfDeath[col].unique())

['Meningitis' 'Neoplasms' 'Fire, heat, and hot substances' 'Malaria'
 'Drowning' 'Interpersonal violence' 'HIV/AIDS' 'Drug use disorders'
 'Tuberculosis' 'Road injuries' 'Maternal disorders'
 'Lower respiratory infections' 'Neonatal disorders'
 'Alcohol use disorders' 'Exposure to forces of nature'
 'Diarrheal diseases' 'Environmental heat and cold exposure'
 'Nutritional deficiencies' 'Self-harm' 'Conflict and terrorism'
 'Diabetes mellitus' 'Poisonings' 'Protein-energy malnutrition'
 'Terrorism (deaths)' 'Cardiovascular diseases' 'Chronic kidney disease'
 'Chronic respiratory diseases'
 'Cirrhosis and other chronic liver diseases' 'Digestive diseases'
 'Acute hepatitis' "Alzheimer's disease and other dementias"
 "Parkinson's disease" 'Number of executions (Amnesty International)']
['Deaths - Meningitis - Sex: Both - Age: All Ages (Number)'
 'Deaths - Neoplasms - Sex: Both - Age: All Ages (Number)'
 'Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)'
 'Deaths - Malaria - Sex: Both - Age: All Ages (Number)'
 'Deaths - Drowning - Sex: Both - Age: All Ages (Number)'
 'Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)'
 'Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)'
 'Deaths - Drug use disorders - Sex: Both - Age: All Ages (Number)'
 'Deaths - Tuberculosis - Sex: Both - Age: All Ages (Number)'
 'Deaths - Road injuries - Sex: Both - Age: All Ages (Number)'
 'Deaths - Maternal disorders - Sex: Both - Age: All Ages (Number)'
 'Deaths - Lower respiratory infections - Sex: Both - Age: All Ages (Number)'
 'Deaths - Neonatal disorders - Sex: Both - Age: All Ages (Number)'
 'Deaths - Alcohol use disorders - Sex: Both - Age: All Ages (Number)'
 'Deaths - Exposure to forces of nature - Sex: Both - Age: All Ages (Number)'
 'Deaths - Diarrheal diseases - Sex: Both - Age: All Ages (Number)'
 'Deaths - Environmental heat and cold exposure - Sex: Both - Age: All Ages (Number)'
 'Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)'
 'Deaths - Self-harm - Sex: Both - Age: All Ages (Number)'
 'Deaths - Conflict and terrorism - Sex: Both - Age: All Ages (Number)'
 'Deaths - Diabetes mellitus - Sex: Both - Age: All Ages (Number)'
 'Deaths - Poisonings - Sex: Both - Age: All Ages (Number)'
 'Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number)'
 'Deaths - Terrorism (deaths) ---'
 'Deaths - Cardiovascular diseases - Sex: Both - Age: All Ages (Number)'
 'Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number)'
 'Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number)'
 'Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number)'
 'Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number)'
 'Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number)'
 "Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)"
 "Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)"
 'Deaths - Number of executions (Amnesty International) ---']
[ 2933. 15925.   481. ... 22106. 20722. 17810.]
['Afghanistan' 'Albania' 'Algeria' 'America' 'American Samoa' 'Andorra'
 'Angola' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Australia'
 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh' 'Barbados'
 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'Brunei' 'Bulgaria'
 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon' 'Canada' 'Cape Verde'
 'Central African Republic' 'Chad' 'Chile' 'China' 'Colombia' 'Comoros'
 'Congo' 'Cook Islands' 'Costa Rica' 'Croatia' 'Cuba' 'Cyprus' 'Czechia'
 'Democratic Republic of Congo' 'Denmark' 'Djibouti' 'Dominica'
 'Dominican Republic' 'East Timor' 'Ecuador' 'Egypt' 'El Salvador'
 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia' 'Fiji'
 'Finland' 'France' 'French Guiana' 'French Polynesia' 'Gabon' 'Gambia'
 'Georgia' 'Germany' 'Ghana' 'Greece' 'Greenland' 'Grenada' 'Guadeloupe'
 'Guam' 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti' 'Honduras'
 'Hong Kong' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran' 'Iraq'
 'Ireland' 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan'
 'Kenya' 'Kiribati' 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia'
 'Lebanon' 'Lesotho' 'Liberia' 'Libya' 'Lithuania' 'Luxembourg' 'Macau'
 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta'
 'Marshall Islands' 'Martinique' 'Mauritania' 'Mauritius' 'Mexico'
 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Morocco' 'Mozambique'
 'Myanmar' 'Namibia' 'Nauru' 'Nepal' 'Netherlands' 'New Caledonia'
 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'Niue' 'North Korea'
 'North Macedonia' 'Northern Mariana Islands' 'Norway' 'Oman' 'Pakistan'
 'Palau' 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru'
 'Philippines' 'Poland' 'Portugal' 'Puerto Rico' 'Qatar' 'Romania'
 'Russia' 'Rwanda' 'Saint Kitts and Nevis' 'Saint Lucia'
 'Saint Vincent and the Grenadines' 'Samoa' 'San Marino'
 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia' 'Seychelles'
 'Sierra Leone' 'Singapore' 'Slovakia' 'Slovenia' 'Solomon Islands'
 'Somalia' 'South Africa' 'South Korea' 'South Sudan' 'Spain' 'Sri Lanka'
 'Sudan' 'Suriname' 'Sweden' 'Switzerland' 'Syria' 'Taiwan' 'Tajikistan'
 'Tanzania' 'Thailand' 'Togo' 'Tokelau' 'Tonga' 'Trinidad and Tobago'
 'Tunisia' 'Turkey' 'Turkmenistan' 'Tuvalu' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'United Kingdom' 'United States'
 'United States Virgin Islands' 'Uruguay' 'Uzbekistan' 'Vanuatu'
 'Venezuela' 'Vietnam' 'Wallis and Futuna' 'Western Sahara' 'Yemen'
 'Zaire' 'Zambia' 'Zimbabwe']
['AFG' 'ALB' 'DZA' nan 'ASM' 'AND' 'AGO' 'ATG' 'ARG' 'ARM' 'AUS' 'AUT'
 'AZE' 'BHS' 'BHR' 'BGD' 'BRB' 'BLR' 'BEL' 'BLZ' 'BEN' 'BMU' 'BTN' 'BOL'
 'BIH' 'BWA' 'BRA' 'BRN' 'BGR' 'BFA' 'BDI' 'KHM' 'CMR' 'CAN' 'CPV' 'CAF'
 'TCD' 'CHL' 'CHN' 'COL' 'COM' 'COG' 'COK' 'CRI' 'HRV' 'CUB' 'CYP' 'CZE'
 'COD' 'DNK' 'DJI' 'DMA' 'DOM' 'ECU' 'EGY' 'SLV' 'GNQ' 'ERI' 'EST' 'SWZ'
 'ETH' 'FJI' 'FIN' 'FRA' 'GUF' 'PYF' 'GAB' 'GMB' 'GEO' 'DEU' 'GHA' 'GRC'
 'GRL' 'GRD' 'GLP' 'GUM' 'GTM' 'GIN' 'GNB' 'GUY' 'HTI' 'HND' 'HKG' 'HUN'
 'ISL' 'IND' 'IDN' 'IRN' 'IRQ' 'IRL' 'ISR' 'ITA' 'JAM' 'JPN' 'JOR' 'KAZ'
 'KEN' 'KIR' 'OWID_KOS' 'KWT' 'KGZ' 'LAO' 'LVA' 'LBN' 'LSO' 'LBR' 'LBY'
 'LTU' 'LUX' 'MDG' 'MWI' 'MYS' 'MDV' 'MLI' 'MLT' 'MHL' 'MTQ' 'MRT' 'MUS'
 'MEX' 'MDA' 'MCO' 'MNG' 'MNE' 'MAR' 'MOZ' 'MMR' 'NAM' 'NRU' 'NPL' 'NLD'
 'NCL' 'NZL' 'NIC' 'NER' 'NGA' 'NIU' 'PRK' 'MKD' 'MNP' 'NOR' 'OMN' 'PAK'
 'PLW' 'PSE' 'PAN' 'PNG' 'PRY' 'PER' 'PHL' 'POL' 'PRT' 'PRI' 'QAT' 'ROU'
 'RUS' 'RWA' 'KNA' 'LCA' 'VCT' 'WSM' 'SMR' 'STP' 'SAU' 'SEN' 'SRB' 'SYC'
 'SLE' 'SGP' 'SVK' 'SVN' 'SLB' 'SOM' 'ZAF' 'KOR' 'SSD' 'ESP' 'LKA' 'SDN'
 'SUR' 'SWE' 'CHE' 'SYR' 'TWN' 'TJK' 'TZA' 'THA' 'TGO' 'TKL' 'TON' 'TTO'
 'TUN' 'TUR' 'TKM' 'TUV' 'UGA' 'UKR' 'ARE' 'GBR' 'USA' 'VIR' 'URY' 'UZB'
 'VUT' 'VEN' 'VNM' 'WLF' 'ESH' 'YEM' 'ZMB' 'ZWE']
[2007 2008 2009 2011 2012 2013 2014 2015 2016 1990 1991 1992 1993 1994
 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2010 2017
 2018 2019]

In [7]:
#check all nulls in df
causeOfDeath.isnull().sum()

Causes name                    0
Causes Full Description        0
Death Numbers              11187
Entity                         0
Code                        1485
Year                           0
dtype: int64

In [8]:
#EDA second set
annualDeathCases.head()

,Entity,Code,Year,Number of executions (Amnesty International),Deaths - Meningitis - Sex: Both - Age: All Ages (Number),Deaths - Neoplasms - Sex: Both - Age: All Ages (Number),"Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)",Deaths - Malaria - Sex: Both - Age: All Ages (Number),Deaths - Drowning - Sex: Both - Age: All Ages (Number),Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number),...,Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number),Terrorism (deaths),Deaths - Cardiovascular diseases - Sex: Both - Age: All Ages (Number),Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number),Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number),Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number),Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number),Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number),Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number),Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)
0,Afghanistan,AFG,2007,15,2933.0,15925.0,481.0,393.0,2127.0,3657.0,...,2439.0,1199.0,53962.0,4490.0,7222.0,3346.0,6458.0,3437.0,1402.0,450.0
1,Afghanistan,AFG,2008,17,2731.0,16148.0,462.0,255.0,1973.0,3785.0,...,2231.0,1092.0,54051.0,4534.0,7143.0,3316.0,6408.0,3005.0,1424.0,455.0
2,Afghanistan,AFG,2009,0,2460.0,16383.0,448.0,239.0,1852.0,3874.0,...,1998.0,1065.0,53964.0,4597.0,7045.0,3291.0,6358.0,2663.0,1449.0,460.0
3,Afghanistan,AFG,2011,2,2327.0,17094.0,448.0,390.0,1775.0,4170.0,...,1805.0,1525.0,54347.0,4785.0,6916.0,3318.0,6370.0,2365.0,1508.0,473.0
4,Afghanistan,AFG,2012,14,2254.0,17522.0,445.0,94.0,1716.0,4245.0,...,1667.0,3521.0,54868.0,4846.0,6878.0,3353.0,6398.0,2264.0,1544.0,482.0

In [9]:
#shape of df
print(annualDeathCases.shape)

(8254, 36)

In [10]:
#get col datatype and nulls
print(annualDeathCases.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8254 entries, 0 to 8253
Data columns (total 36 columns):
 #   Column                                                                                    Non-Null Count  Dtype
---  ------                                                                                    --------------  -----
 0   Entity                                                                                    8254 non-null   object
 1   Code                                                                                      6206 non-null   object
 2   Year                                                                                      8254 non-null   int64
 3   Number of executions (Amnesty International)                                              267 non-null    object
 4   Deaths - Meningitis - Sex: Both - Age: All Ages (Number)                                  8010 non-null   float64
 5   Deaths - Neoplasms - Sex: Both - Age: All Ages (Number)                                   8010 non-null   float64
 6   Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)              8010 non-null   float64
 7   Deaths - Malaria - Sex: Both - Age: All Ages (Number)                                     8010 non-null   float64
 8   Deaths - Drowning - Sex: Both - Age: All Ages (Number)                                    8010 non-null   float64
 9   Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)                      8010 non-null   float64
 10  Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)                                    8010 non-null   float64
 11  Deaths - Drug use disorders - Sex: Both - Age: All Ages (Number)                          8010 non-null   float64
 12  Deaths - Tuberculosis - Sex: Both - Age: All Ages (Number)                                8010 non-null   float64
 13  Deaths - Road injuries - Sex: Both - Age: All Ages (Number)                               8010 non-null   float64
 14  Deaths - Maternal disorders - Sex: Both - Age: All Ages (Number)                          8010 non-null   float64
 15  Deaths - Lower respiratory infections - Sex: Both - Age: All Ages (Number)                8010 non-null   float64
 16  Deaths - Neonatal disorders - Sex: Both - Age: All Ages (Number)                          8010 non-null   float64
 17  Deaths - Alcohol use disorders - Sex: Both - Age: All Ages (Number)                       8010 non-null   float64
 18  Deaths - Exposure to forces of nature - Sex: Both - Age: All Ages (Number)                8010 non-null   float64
 19  Deaths - Diarrheal diseases - Sex: Both - Age: All Ages (Number)                          8010 non-null   float64
 20  Deaths - Environmental heat and cold exposure - Sex: Both - Age: All Ages (Number)        8010 non-null   float64
 21  Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)                    8010 non-null   float64
 22  Deaths - Self-harm - Sex: Both - Age: All Ages (Number)                                   8010 non-null   float64
 23  Deaths - Conflict and terrorism - Sex: Both - Age: All Ages (Number)                      8010 non-null   float64
 24  Deaths - Diabetes mellitus - Sex: Both - Age: All Ages (Number)                           8010 non-null   float64
 25  Deaths - Poisonings - Sex: Both - Age: All Ages (Number)                                  8010 non-null   float64
 26  Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number)                 8010 non-null   float64
 27  Terrorism (deaths)                                                                        2891 non-null   float64
 28  Deaths - Cardiovascular diseases - Sex: Both - Age: All Ages (Number)                     8010 non-null   float64
 29  Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number)                      8010 non-null   float64
 30  Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number)                8010 non-null   float64
 31  Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number)  8010 non-null   float64
 32  Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number)                          8010 non-null   float64
 33  Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number)                             8010 non-null   float64
 34  Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)     8010 non-null   float64
 35  Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)                         8010 non-null   float64
dtypes: float64(32), int64(1), object(3)
memory usage: 2.3+ MB
None

In [11]:
# use to see all unique values
for col in annualDeathCases:
  print(annualDeathCases[col].unique())

['Afghanistan' 'Africa' 'African Region' 'African Union' 'Albania'
 'Algeria' 'America' 'American Samoa' 'Andean Latin America' 'Andorra'
 'Angola' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Asia' 'Australasia'
 'Australasia & Oceania' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas'
 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin'
 'Bermuda' 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina'
 'Bosnia-Herzegovina' 'Botswana' 'Brazil' 'Brunei' 'Bulgaria'
 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon' 'Canada' 'Cape Verde'
 'Caribbean' 'Central African Republic' 'Central America & Caribbean'
 'Central Asia' 'Central Europe'
 'Central Europe, Eastern Europe, and Central Asia'
 'Central Latin America' 'Central sub-Saharan Africa' 'Chad' 'Chile'
 'China' 'Colombia' 'Commonwealth' 'Commonwealth High Income'
 'Commonwealth Low Income' 'Commonwealth Middle Income' 'Comoros' 'Congo'
 'Cook Islands' 'Costa Rica' "Cote d'Ivoire" 'Croatia' 'Cuba' 'Cyprus'
 'Czechia' 'Czechoslovakia' 'Democratic Republic of Congo' 'Denmark'
 'Djibouti' 'Dominica' 'Dominican Republic' 'East Asia'
 'East Asia & Pacific - World Bank region' 'East Germany (GDR)'
 'East Timor' 'Eastern Europe' 'Eastern Mediterranean Region'
 'Eastern sub-Saharan Africa' 'Ecuador' 'Egypt' 'El Salvador' 'England'
 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia' 'Europe'
 'Europe & Central Asia - World Bank region' 'European Region'
 'European Union' 'Fiji' 'Finland' 'France' 'French Guiana'
 'French Polynesia' 'G20' 'Gabon' 'Gambia' 'Georgia' 'Germany' 'Ghana'
 'Greece' 'Greenland' 'Grenada' 'Guadeloupe' 'Guam' 'Guatemala' 'Guinea'
 'Guinea-Bissau' 'Guyana' 'Haiti' 'High SDI' 'High-income'
 'High-income Asia Pacific' 'High-income North America' 'High-middle SDI'
 'Honduras' 'Hong Kong' 'Hungary' 'Iceland' 'India' 'Indonesia'
 'International' 'Iran' 'Iraq' 'Ireland' 'Israel' 'Italy' 'Jamaica'
 'Japan' 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati' 'Kosovo' 'Kuwait'
 'Kyrgyzstan' 'Laos' 'Latin America & Caribbean - World Bank region'
 'Latvia' 'Lebanon' 'Lesotho' 'Liberia' 'Libya' 'Lithuania' 'Low SDI'
 'Low-middle SDI' 'Luxembourg' 'Macau' 'Madagascar' 'Malawi' 'Malaysia'
 'Maldives' 'Mali' 'Malta' 'Marshall Islands' 'Martinique' 'Mauritania'
 'Mauritius' 'Mexico' 'Micronesia (country)' 'Middle East & North Africa'
 'Middle SDI' 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Morocco'
 'Mozambique' 'Myanmar' 'Namibia' 'Nauru' 'Nepal' 'Netherlands'
 'New Caledonia' 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'Niue'
 'Nordic Region' 'North Africa and Middle East' 'North America'
 'North Korea' 'North Macedonia' 'Northern Ireland'
 'Northern Mariana Islands' 'Norway' 'OECD Countries' 'Oceania' 'Oman'
 'Pakistan' 'Palau' 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay'
 'Peru' 'Philippines' 'Poland' 'Portugal' 'Puerto Rico' 'Qatar'
 'Region of the Americas' 'Romania' 'Russia' 'Rwanda'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Vincent and the Grenadines'
 'Samoa' 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Scotland'
 'Senegal' 'Serbia' 'Serbia-Montenegro' 'Seychelles' 'Sierra Leone'
 'Singapore' 'Slovakia' 'Slovenia' 'Solomon Islands' 'Somalia'
 'South Africa' 'South America' 'South Asia'
 'South Asia - World Bank region' 'South Korea' 'South Sudan'
 'South-East Asia Region' 'Southeast Asia'
 'Southeast Asia, East Asia, and Oceania' 'Southern Latin America'
 'Southern sub-Saharan Africa' 'Spain' 'Sri Lanka' 'Sub-Saharan Africa'
 'Sub-Saharan Africa - World Bank region' 'Sudan' 'Suriname' 'Sweden'
 'Switzerland' 'Syria' 'Taiwan' 'Tajikistan' 'Tanzania' 'Thailand' 'Timor'
 'Togo' 'Tokelau' 'Tonga' 'Trinidad and Tobago' 'Tropical Latin America'
 'Tunisia' 'Turkey' 'Turkmenistan' 'Tuvalu' 'USSR' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'United Kingdom' 'United States'
 'United States Virgin Islands' 'Uruguay' 'Uzbekistan' 'Vanuatu'
 'Venezuela' 'Vietnam' 'Wales' 'Wallis and Futuna' 'West Germany (FRG)'
 'Western Europe' 'Western Pacific Region' 'Western Sahara'
 'Western sub-Saharan Africa' 'World' 'World (excluding China)'
 'World Bank High Income' 'World Bank Low Income'
 'World Bank Lower Middle Income' 'World Bank Upper Middle Income' 'Yemen'
 'Yugoslavia' 'Zaire' 'Zambia' 'Zimbabwe']
['AFG' nan 'ALB' 'DZA' 'ASM' 'AND' 'AGO' 'ATG' 'ARG' 'ARM' 'AUS' 'AUT'
 'AZE' 'BHS' 'BHR' 'BGD' 'BRB' 'BLR' 'BEL' 'BLZ' 'BEN' 'BMU' 'BTN' 'BOL'
 'BIH' 'BWA' 'BRA' 'BRN' 'BGR' 'BFA' 'BDI' 'KHM' 'CMR' 'CAN' 'CPV' 'CAF'
 'TCD' 'CHL' 'CHN' 'COL' 'COM' 'COG' 'COK' 'CRI' 'CIV' 'HRV' 'CUB' 'CYP'
 'CZE' 'OWID_CZS' 'COD' 'DNK' 'DJI' 'DMA' 'DOM' 'ECU' 'EGY' 'SLV' 'GNQ'
 'ERI' 'EST' 'SWZ' 'ETH' 'FJI' 'FIN' 'FRA' 'GUF' 'PYF' 'GAB' 'GMB' 'GEO'
 'DEU' 'GHA' 'GRC' 'GRL' 'GRD' 'GLP' 'GUM' 'GTM' 'GIN' 'GNB' 'GUY' 'HTI'
 'HND' 'HKG' 'HUN' 'ISL' 'IND' 'IDN' 'IRN' 'IRQ' 'IRL' 'ISR' 'ITA' 'JAM'
 'JPN' 'JOR' 'KAZ' 'KEN' 'KIR' 'OWID_KOS' 'KWT' 'KGZ' 'LAO' 'LVA' 'LBN'
 'LSO' 'LBR' 'LBY' 'LTU' 'LUX' 'MDG' 'MWI' 'MYS' 'MDV' 'MLI' 'MLT' 'MHL'
 'MTQ' 'MRT' 'MUS' 'MEX' 'FSM' 'MDA' 'MCO' 'MNG' 'MNE' 'MAR' 'MOZ' 'MMR'
 'NAM' 'NRU' 'NPL' 'NLD' 'NCL' 'NZL' 'NIC' 'NER' 'NGA' 'NIU' 'PRK' 'MKD'
 'MNP' 'NOR' 'OMN' 'PAK' 'PLW' 'PSE' 'PAN' 'PNG' 'PRY' 'PER' 'PHL' 'POL'
 'PRT' 'PRI' 'QAT' 'ROU' 'RUS' 'RWA' 'KNA' 'LCA' 'VCT' 'WSM' 'SMR' 'STP'
 'SAU' 'SEN' 'SRB' 'SYC' 'SLE' 'SGP' 'SVK' 'SVN' 'SLB' 'SOM' 'ZAF' 'KOR'
 'SSD' 'ESP' 'LKA' 'SDN' 'SUR' 'SWE' 'CHE' 'SYR' 'TWN' 'TJK' 'TZA' 'THA'
 'TLS' 'TGO' 'TKL' 'TON' 'TTO' 'TUN' 'TUR' 'TKM' 'TUV' 'OWID_USS' 'UGA'
 'UKR' 'ARE' 'GBR' 'USA' 'VIR' 'URY' 'UZB' 'VUT' 'VEN' 'VNM' 'WLF' 'ESH'
 'OWID_WRL' 'YEM' 'OWID_YGS' 'ZMB' 'ZWE']
[2007 2008 2009 2011 2012 2013 2014 2015 2016 1990 1991 1992 1993 1994
 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2010 2017
 2018 2019]
['15' '17' '0' '2' '14' '6' '1' nan '5' '3' '9' '4' '10' '470' '>1000'
 '22' '44' '317' '346' '388' '252' '360' '314' '369' '289' '977' '156'
 '33' '34' '120' '68' '129' '169' '61' '26' '88' '7' '8' '11' '18' '>1'
 '60' '30' '135' '36' '326' '87' '143' '102' '69' '27' '82' '79' '90'
 '158' '154' '25' '19' '21' '23' '42' '37' '52' '46' '43' '39' '35' '28'
 '20' '1248' '2390' '712' '521' '670' '680' '767' '603' '1626' '613' '13'
 '53' '41']
[2933. 2731. 2460. ... 1457. 1460. 1450.]
[15925. 16148. 16383. ... 11744. 12038. 12353.]
[481. 462. 448. ... 330. 417. 590.]
[ 393.  255.  239. ... 2116. 2088. 2068.]
[2127. 1973. 1852. ...  392.  420.  770.]
[3657. 3785. 3874. ... 1363. 1396. 1434.]
[  148.   157.   167. ... 24846. 22106. 20722.]
[  252.   261.   270. ... 24554. 25763. 26734.]
[ 4995.  4790.  4579. ... 10762. 10545. 10465.]
[7425. 7355. 7290. ... 2373. 2509. 2554.]
[4990. 5020. 5013. ...  714. 1362. 1312.]
[27672. 25800. 24340. ... 12961. 12860. 12897.]
[23890. 23792. 23672. ...  8901.  8697.  8609.]
[  111.   114.   115. ... 71099. 72670. 73977.]
[ 296. 1317.  101. ... 3645.  554.  345.]
[9320. 8275. 7359. ... 4948. 4745. 4635.]
[   57.    58.   103. ... 17611. 17353. 17332.]
[2488. 2277. 2040. ... 2977. 3019. 2990.]
[1310. 1330. 1342. ... 2297. 2338. 2403.]
[ 8220.  6895.  7617. ... 30779. 13402.   372.]
[3189. 3261. 3336. ... 3313. 3381. 3460.]
[513. 495. 483. ... 447. 301. 304.]
[2439. 2231. 1998. ... 2962. 2890. 2855.]
[1.1990e+03 1.0920e+03 1.0650e+03 1.5250e+03 3.5210e+03 3.7090e+03
 5.4140e+03 6.2160e+03 6.1420e+03 1.2000e+01 6.8000e+01 4.9000e+01
        nan 2.2000e+01 5.0000e+00 3.1000e+01 4.0000e+00 8.0000e+00
 3.9000e+01 3.8000e+01 1.7400e+02 7.4000e+01 1.6300e+02 2.7500e+02
 3.6700e+02 7.3200e+02 1.1570e+03 6.0920e+03 0.0000e+00 1.0000e+00
 7.0000e+00 2.6000e+01 6.0000e+00 3.0000e+00 4.2000e+01 2.3600e+02
 5.0000e+02 4.1800e+02 5.2900e+02 4.2660e+03 9.5200e+02 4.6700e+02
 5.2800e+02 6.2400e+02 6.1500e+02 2.6900e+02 1.6600e+02 2.2800e+02
 1.8500e+02 2.4100e+02 2.4900e+02 2.0400e+02 1.0900e+02 2.5000e+01
 3.0000e+01 1.0100e+02 3.7000e+01 2.1000e+01 9.0000e+00 1.4700e+02
 6.9000e+01 9.7000e+01 1.0800e+02 5.2000e+01 1.8000e+01 3.4000e+01
 2.9900e+02 1.7800e+02 8.4600e+02 5.9000e+01 2.0000e+00 3.3000e+01
 8.6000e+01 1.5000e+01 2.0000e+01 2.3000e+01 1.8600e+02 1.6000e+01
 7.6000e+01 6.6000e+01 3.5000e+01 8.9000e+01 1.4000e+01 1.1000e+01
 5.7000e+01 4.3000e+01 4.4000e+01 1.9000e+01 1.3000e+01 3.6000e+01
 5.5000e+01 2.8000e+01 6.2000e+01 5.3000e+01 1.1700e+02 6.1000e+01
 2.6500e+02 5.8300e+02 1.3710e+03 3.8600e+02 3.9200e+02 6.7000e+01
 1.1600e+02 4.7000e+01 2.2300e+02 6.4000e+01 2.2500e+02 1.0000e+02
 7.8900e+02 9.3100e+02 4.6000e+01 1.2000e+02 7.5100e+02 1.7100e+02
 1.8900e+02 6.0100e+02 4.0600e+02 7.1400e+02 1.1200e+02 1.8400e+02
 8.1000e+01 8.8000e+01 7.3000e+01 3.2000e+02 1.2200e+02 9.4000e+01
 5.6000e+01 1.0000e+01 1.3600e+02 1.7200e+02 3.0600e+02 4.0000e+01
 1.7000e+02 7.7000e+01 1.0300e+02 2.7000e+01 6.0000e+01 3.2200e+02
 1.2300e+02 5.0000e+01 6.9400e+02 7.4200e+02 6.3100e+02 2.1800e+02
 5.2100e+02 6.1100e+02 1.2300e+03 5.9200e+02 2.6200e+02 4.2600e+02
 5.7600e+02 3.5600e+02 8.3000e+01 1.4500e+02 7.9000e+01 8.5000e+01
 1.0700e+02 1.6800e+02 1.3700e+02 1.4300e+02 1.0400e+02 8.4000e+01
 1.7000e+01 4.1000e+01 4.5000e+01 2.3700e+02 1.5400e+02 7.2000e+01
 3.1900e+02 8.2400e+02 1.1800e+02 2.8800e+02 1.5000e+02 3.6600e+02
 3.7100e+02 5.3200e+02 5.9600e+02 3.2000e+01 2.7300e+02 1.1000e+02
 1.5800e+02 1.6700e+02 1.1500e+02 4.4000e+02 4.0200e+02 2.9400e+02
 5.1800e+02 3.3700e+02 6.0800e+02 2.3500e+02 1.7900e+02 1.5100e+02
 1.4670e+03 7.9000e+02 3.4300e+02 8.2900e+02 6.0900e+02 1.7300e+02
 1.3400e+02 1.6500e+02 9.2000e+01 2.4300e+02 8.7700e+02 1.6100e+02
 3.3000e+02 1.3300e+02 4.8000e+01 2.7900e+02 1.6200e+02 9.5000e+01
 2.9000e+01 2.0600e+02 8.7000e+01 6.2600e+02 7.7400e+02 2.6400e+02
 3.8700e+02 9.0700e+02 1.1130e+03 1.1520e+03 3.8900e+02 3.6100e+02
 5.6900e+02 8.5300e+02 3.9800e+02 4.6900e+02 6.7100e+02 6.6000e+02
 5.9900e+02 4.7200e+02 3.3400e+02 4.6600e+02 7.2200e+02 8.1200e+02
 4.9900e+02 4.9000e+02 4.6500e+02 1.0200e+02 1.4600e+02 2.4600e+02
 2.4000e+01 6.6670e+03 2.8640e+03 2.5850e+03 2.0740e+03 1.8700e+03
 2.6860e+03 7.0410e+03 1.3965e+04 8.8850e+03 1.2207e+04 7.5000e+01
 1.5600e+02 1.0600e+02 3.9100e+02 2.1710e+03 3.3840e+03 4.6160e+03
 6.4760e+03 1.4100e+02 1.5500e+02 2.2600e+02 2.0700e+02 3.1500e+02
 2.8100e+02 1.2600e+02 1.1300e+02 9.8000e+01 1.4200e+02 1.9000e+02
 1.1100e+02 2.3200e+02 6.8900e+02 6.3400e+02 2.8900e+02 1.3100e+02
 1.2500e+02 1.8100e+02 9.6000e+01 2.2900e+02 7.7800e+02 5.4400e+02
 1.8790e+03 2.0650e+03 1.0200e+03 9.6100e+02 4.6910e+03 1.0790e+03
 6.7200e+02 1.1750e+03 1.0630e+03 2.5580e+03 3.9180e+03 5.0320e+03
 7.1800e+03 3.4670e+03 2.9820e+03 2.6630e+03 2.6510e+03 5.0330e+03
 1.0164e+04 2.0080e+04 1.7854e+04 1.9205e+04 1.0819e+04 2.7100e+02
 7.1000e+01 9.0000e+01 1.3900e+02 9.1000e+01 4.8600e+02 6.3000e+02
 2.1100e+02 5.4000e+01 6.6600e+02 1.4800e+02 8.2000e+01 3.1600e+02
 2.0140e+03 2.1650e+03 1.3500e+02 2.5400e+02 4.4700e+02 1.5080e+03
 7.7810e+03 5.5590e+03 1.8050e+03 2.4000e+02 2.3100e+02 3.0210e+03
 7.0000e+01 6.3000e+01 1.2400e+02 1.4060e+03 1.1840e+03 1.4870e+03
 2.7840e+03 2.4130e+03 1.6080e+03 1.8800e+02 1.5200e+02 3.5400e+02
 7.1200e+02 4.2300e+02 4.4300e+02 1.2700e+02 1.0500e+02 1.1900e+02
 3.0400e+02 1.6990e+03 1.6760e+03 2.8750e+03 1.0760e+03 9.3000e+01
 1.2900e+02 1.7700e+02 1.1460e+03 1.4120e+03 8.1800e+02 4.5700e+02
 4.3200e+02 3.9500e+02 2.0100e+02 2.9000e+02 2.2000e+02 4.1500e+02
 4.9600e+02 3.6200e+02 5.1200e+02 3.2800e+02 6.0700e+02 1.5700e+02
 1.6000e+02 1.5710e+03 1.0270e+03 2.1300e+02 1.2800e+02 2.5800e+02
 4.0800e+02 3.8100e+02 2.9500e+02 3.4400e+02 7.8300e+02 1.5890e+03
 1.4470e+03 1.5830e+03 7.8000e+01 4.3600e+02 1.9120e+03 3.8400e+02
 7.0600e+02 1.8610e+03 2.2380e+03 1.5360e+03 6.5000e+02 7.2500e+02
 1.3170e+03 2.9300e+02 4.3000e+02 5.9300e+02 3.6900e+02 1.9100e+02
 5.8000e+01 1.8000e+02 2.6780e+03 2.5150e+03 2.4470e+03 9.8500e+02
 2.1330e+03 1.9450e+03 1.8150e+03 1.2370e+03 9.0000e+02 1.3780e+03
 1.3670e+03 1.2880e+03 8.0200e+02 1.6160e+03 1.3650e+03 2.9370e+03
 3.6860e+03 3.5170e+03 3.5650e+03 3.6950e+03 3.7250e+03 6.5860e+03
 7.0700e+03 8.3580e+03 8.3000e+03 7.8030e+03 7.6640e+03 6.3300e+02
 9.0800e+02 5.8100e+02 5.6200e+02 5.7400e+02 6.7300e+02 3.9000e+02
 3.1200e+02 2.7000e+02 3.3500e+02 4.5900e+02 3.1100e+02 3.9600e+02
 2.6600e+02 2.6000e+02 4.0300e+02 4.8200e+02 4.5300e+02 7.2300e+02
 7.0200e+02 6.4600e+02 6.3900e+02 8.1100e+02 1.9300e+02 1.5050e+03
 1.0340e+03 9.8400e+02 8.2700e+02 6.8000e+02 2.1200e+02 4.4900e+02
 1.9500e+02 1.0120e+03 4.1000e+02 3.5300e+02 1.3470e+03 2.4420e+03
 3.2320e+03 1.3200e+03 2.1880e+03 1.4370e+03 8.8500e+02 1.0260e+03
 1.1690e+03 1.0410e+03 5.5500e+02 3.1700e+02 3.7900e+02 9.7200e+02
 1.3830e+03 1.4750e+03 1.7310e+03 8.3000e+02 2.9960e+03 3.8570e+03
 1.3351e+04 1.0763e+04 6.6520e+03 6.7120e+03 2.0500e+02 5.4600e+02
 2.1000e+02 1.8200e+02 5.8900e+02 4.8400e+02 1.5680e+03 3.3120e+03
 3.9240e+03 2.8100e+03 2.0260e+03 1.3000e+02 1.9400e+02 2.0900e+02
 2.5500e+02 1.9200e+02 3.0800e+02 1.2330e+03 9.8200e+02 2.4700e+02
 1.0060e+03 2.2200e+02 4.1300e+02 2.3900e+02 2.9700e+02 8.0000e+01
 1.3960e+03 7.6500e+02 3.0080e+03 1.9600e+02 2.3800e+02 7.1480e+03
 8.4290e+03 9.7420e+03 7.6900e+03 6.1030e+03 6.9660e+03 1.0924e+04
 4.6880e+03 3.3930e+03 4.4030e+03 7.7290e+03 4.8050e+03 3.3170e+03
 5.7430e+03 6.3310e+03 9.3800e+03 1.2824e+04 9.1570e+03 9.2730e+03
 7.8270e+03 8.2460e+03 1.5497e+04 2.2273e+04 4.4490e+04 3.8853e+04
 3.4871e+04 2.6445e+04 3.4500e+02 4.6100e+02 1.0560e+03 1.3530e+03
 2.3740e+03 1.5170e+03 7.6200e+02]
[53962. 54051. 53964. ... 17187. 17460. 17810.]
[4490. 4534. 4597. ... 2006. 2108. 2160.]
[7222. 7143. 7045. ... 2751. 2788. 2891.]
[3346. 3316. 3291. ... 2062. 1962. 2065.]
[6458. 6408. 6358. ... 4264. 4342. 4377.]
[3437. 3005. 2663. ...  846.  734.  502.]
[1402. 1424. 1449. ...  731.  754.  795.]
[   450.    455.    460. ... 126187. 129622. 134442.]

In [12]:
#check all nulls in df
annualDeathCases.isnull().sum()

Entity                                                                                         0
Code                                                                                        2048
Year                                                                                           0
Number of executions (Amnesty International)                                                7987
Deaths - Meningitis - Sex: Both - Age: All Ages (Number)                                     244
Deaths - Neoplasms - Sex: Both - Age: All Ages (Number)                                      244
Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)                 244
Deaths - Malaria - Sex: Both - Age: All Ages (Number)                                        244
Deaths - Drowning - Sex: Both - Age: All Ages (Number)                                       244
Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)                         244
Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)                                       244
Deaths - Drug use disorders - Sex: Both - Age: All Ages (Number)                             244
Deaths - Tuberculosis - Sex: Both - Age: All Ages (Number)                                   244
Deaths - Road injuries - Sex: Both - Age: All Ages (Number)                                  244
Deaths - Maternal disorders - Sex: Both - Age: All Ages (Number)                             244
Deaths - Lower respiratory infections - Sex: Both - Age: All Ages (Number)                   244
Deaths - Neonatal disorders - Sex: Both - Age: All Ages (Number)                             244
Deaths - Alcohol use disorders - Sex: Both - Age: All Ages (Number)                          244
Deaths - Exposure to forces of nature - Sex: Both - Age: All Ages (Number)                   244
Deaths - Diarrheal diseases - Sex: Both - Age: All Ages (Number)                             244
Deaths - Environmental heat and cold exposure - Sex: Both - Age: All Ages (Number)           244
Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)                       244
Deaths - Self-harm - Sex: Both - Age: All Ages (Number)                                      244
Deaths - Conflict and terrorism - Sex: Both - Age: All Ages (Number)                         244
Deaths - Diabetes mellitus - Sex: Both - Age: All Ages (Number)                              244
Deaths - Poisonings - Sex: Both - Age: All Ages (Number)                                     244
Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number)                    244
Terrorism (deaths)                                                                          5363
Deaths - Cardiovascular diseases - Sex: Both - Age: All Ages (Number)                        244
Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number)                         244
Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number)                   244
Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number)     244
Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number)                             244
Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number)                                244
Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)        244
Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)                            244
dtype: int64